#ifndef __ISAEXE__  // isaexe.h
#define __ISAEXE__

//
//  Interface.
//
#define SET_FUNC(Name)  Status IsaExe##Name(ISA_OBJ *pISA_OBJ);

#include "disassember.h"

SET_FUNC(MOV);
SET_FUNC(PUSH);
SET_FUNC(POP);
SET_FUNC(XCHG);
SET_FUNC(IN);
SET_FUNC(OUT);
SET_FUNC(XLAT);
SET_FUNC(LEA);
SET_FUNC(LDS);
SET_FUNC(LES);
SET_FUNC(LAHF);
SET_FUNC(SAHF);
SET_FUNC(PUSHF);
SET_FUNC(POPF);


// ARITHMETIC
SET_FUNC(ADD);
SET_FUNC(ADC);
SET_FUNC(INC);
SET_FUNC(AAA);
SET_FUNC(BAA);
SET_FUNC(SUB);
SET_FUNC(SSB);
SET_FUNC(DEC);
SET_FUNC(NEG);
SET_FUNC(CMP);
SET_FUNC(AAS);
SET_FUNC(DAS);
SET_FUNC(MUL);
SET_FUNC(IMUL);
SET_FUNC(AAM);
SET_FUNC(DIV);
SET_FUNC(IDIV);
SET_FUNC(AAD);
SET_FUNC(CBW);
SET_FUNC(CWD);

// LOGIC
SET_FUNC(NOT);
SET_FUNC(SHL);
SET_FUNC(SAL);
SET_FUNC(SHR);
SET_FUNC(SAR);
SET_FUNC(ROL);
SET_FUNC(ROR);
SET_FUNC(RCL);
SET_FUNC(RCR);
SET_FUNC(AND);
SET_FUNC(TEST);
SET_FUNC(OR);
SET_FUNC(XOR);

// STRING MANIPULATION
SET_FUNC(REP);
SET_FUNC(REPZ);
SET_FUNC(REPNZ);
SET_FUNC(MOVS);
SET_FUNC(CMPS);
SET_FUNC(SCAS);
SET_FUNC(LODS);
SET_FUNC(STOS);

// CONTROL TRANSFER
SET_FUNC(CALL);
SET_FUNC(JMP);
SET_FUNC(RET);
SET_FUNC(JZ);
SET_FUNC(JE);
SET_FUNC(JL);
SET_FUNC(JNGE);
SET_FUNC(JLE);
SET_FUNC(JNG);
SET_FUNC(JB);
SET_FUNC(JNAE);
SET_FUNC(JBE);
SET_FUNC(JNA);
SET_FUNC(JP);
SET_FUNC(JPE);
SET_FUNC(JO);
SET_FUNC(JS);
SET_FUNC(JNE);
SET_FUNC(JNZ);
SET_FUNC(JNL);
SET_FUNC(JGE);
SET_FUNC(JNLE);
SET_FUNC(JAE);
SET_FUNC(JNBE);
SET_FUNC(JA);
SET_FUNC(JNP);
SET_FUNC(JPO);
SET_FUNC(JNO);
SET_FUNC(JNS);
SET_FUNC(LOOP);
SET_FUNC(LOOPZ);
SET_FUNC(LOOPE);
SET_FUNC(LOOPNZ);
SET_FUNC(LOOPNE);
SET_FUNC(JCXZ);
SET_FUNC(INT);
SET_FUNC(INT_3);
SET_FUNC(INTO);
SET_FUNC(IRET);

// PROCESSOR CONTROL
SET_FUNC(CLC);
SET_FUNC(CMC);
SET_FUNC(STC);
SET_FUNC(CLD);
SET_FUNC(STD);
SET_FUNC(CLI);
SET_FUNC(STI);
SET_FUNC(HLT);
SET_FUNC(WAIT);
SET_FUNC(ESC);
SET_FUNC(LOCK);

#endif  //isaexe.h