

#include "opmem.h"
#include "ioports.h"
#include "opreg.h"
#include "disassember.h"


#define EXTERN_FUN(Name)    Status IsaExe##Name(ISA_OBJ *pISA_OBJ)


//
//  Func
//

EXTERN_FUN(MOV)
{
    
    
}
EXTERN_FUN(PUSH)
EXTERN_FUN(POP)
EXTERN_FUN(XCHG)
EXTERN_FUN(IN)
EXTERN_FUN(OUT)
EXTERN_FUN(XLAT)
EXTERN_FUN(LEA)
EXTERN_FUN(LDS)
EXTERN_FUN(LES)
EXTERN_FUN(LAHF)
EXTERN_FUN(SAHF)
EXTERN_FUN(PUSHF)
EXTERN_FUN(POPF)


// ARITHMETIC
EXTERN_FUN(ADD)
EXTERN_FUN(ADC)
EXTERN_FUN(INC)
EXTERN_FUN(AAA)
EXTERN_FUN(BAA)
EXTERN_FUN(SUB)
EXTERN_FUN(SSB)
EXTERN_FUN(DEC)
EXTERN_FUN(NEG)
EXTERN_FUN(CMP)
EXTERN_FUN(AAS)
EXTERN_FUN(DAS)
EXTERN_FUN(MUL)
EXTERN_FUN(IMUL)
EXTERN_FUN(AAM)
EXTERN_FUN(DIV)
EXTERN_FUN(IDIV)
EXTERN_FUN(AAD)
EXTERN_FUN(CBW)
EXTERN_FUN(CWD)

// LOGIC
EXTERN_FUN(NOT)
EXTERN_FUN(SHL)
EXTERN_FUN(SAL)
EXTERN_FUN(SHR)
EXTERN_FUN(SAR)
EXTERN_FUN(ROL)
EXTERN_FUN(ROR)
EXTERN_FUN(RCL)
EXTERN_FUN(RCR)
EXTERN_FUN(AND)
EXTERN_FUN(TEST)
EXTERN_FUN(OR)
EXTERN_FUN(XOR)

// STRING MANIPULATION
EXTERN_FUN(REP)
EXTERN_FUN(REPZ)
EXTERN_FUN(REPNZ)
EXTERN_FUN(MOVS)
EXTERN_FUN(CMPS)
EXTERN_FUN(SCAS)
EXTERN_FUN(LODS)
EXTERN_FUN(STOS)

// CONTROL TRANSFER
EXTERN_FUN(CALL)
EXTERN_FUN(JMP)
EXTERN_FUN(RET)
EXTERN_FUN(JZ)
EXTERN_FUN(JE)
EXTERN_FUN(JL)
EXTERN_FUN(JNGE)
EXTERN_FUN(JLE)
EXTERN_FUN(JNG)
EXTERN_FUN(JB)
EXTERN_FUN(JNAE)
EXTERN_FUN(JBE)
EXTERN_FUN(JNA)
EXTERN_FUN(JP)
EXTERN_FUN(JPE)
EXTERN_FUN(JO)
EXTERN_FUN(JS)
EXTERN_FUN(JNE)
EXTERN_FUN(JNZ)
EXTERN_FUN(JNL)
EXTERN_FUN(JGE)
EXTERN_FUN(JNLE)
EXTERN_FUN(JAE)
EXTERN_FUN(JNBE)
EXTERN_FUN(JA)
EXTERN_FUN(JNP)
EXTERN_FUN(JPO)
EXTERN_FUN(JNO)
EXTERN_FUN(JNS)
EXTERN_FUN(LOOP)
EXTERN_FUN(LOOPZ)
EXTERN_FUN(LOOPE)
EXTERN_FUN(LOOPNZ)
EXTERN_FUN(LOOPNE)
EXTERN_FUN(JCXZ)
EXTERN_FUN(INT)
EXTERN_FUN(INT_3)
EXTERN_FUN(INTO)
EXTERN_FUN(IRET)

// PROCESSOR CONTROL
EXTERN_FUN(CLC)
EXTERN_FUN(CMC)
EXTERN_FUN(STC)
EXTERN_FUN(CLD)
EXTERN_FUN(STD)
EXTERN_FUN(CLI)
EXTERN_FUN(STI)
EXTERN_FUN(HLT)
EXTERN_FUN(WAIT)
EXTERN_FUN(ESC)
EXTERN_FUN(LOCK)